{{- if .Values.VideoReaderJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "video-reader-job"
  labels:
    app: videoprocessor
    component: VideoReaderJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.7.2
  mavenCoordinate: {{ .Values.flink.applications.coordination.group }}:{{ .Values.flink.applications.coordination.artifact }}:{{ .Values.flink.applications.coordination.version }}

  parallelism: {{ .Values.VideoReaderJob.parallelism }}

  state: started

  parameters:
    - name: jobClass
      value: "io.pravega.example.videoprocessor.VideoReaderJob"
    - name: scope
      value: {{ $.Release.Namespace }}
    - name: input-stream
      value: "grid1"
    - name: input-minNumSegments
      value: "6"

    # Flink Job Parameters
#    - name: job.checkpointInterval
#      value: "60000"
#    - name: job.disableCheckpoint
#      value: "false"
#    - name: job.disableOperatorChaining
#      value: "true"
#    - name: rebalance
#      value: "false"
{{- end }}
