mavenCoordinate:
  group: io.pravega.example.video
  artifact: flinkprocessor
  version: 0.1.0

VideoDataGeneratorJob:
  enabled: true
  parallelism: 1
  enableOperatorChaining: "false"
  numCameras: 4
  imageWidth: 100
  framesPerSec: 1.0
  chunkSizeBytes: 10240
  taskManager:
    replicas: 1
    memory: 2G
    cpu: 250m
    taskSlots: 2

MultiVideoGridJob:
  enabled: true
  parallelism: 2
  enableOperatorChaining: "false"
  input:
    stream: video1
    minNumSegments: 6
  output:
    stream: grid1
    minNumSegments: 3
  imageWidth: 75
  framesPerSec: 1.0
  chunkSizeBytes: 524288
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 16G
    cpu: 1000m
    taskSlots: 4

VideoReaderJob:
  enabled: true
  parallelism: 2
  enableOperatorChaining: "false"
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 4G
    cpu: 250m
    taskSlots: 2
