flink:
  cluster:
    replica: 1
    taskManager:
      replicas: 2
      memory: 1024M
      cpu: 900m
      taskSlots: 3
  applications:
    coordination:
      group: io.pravega.example.video
      artifact: flinkprocessor
      version: 0.1.0

VideoDataGeneratorJob:
  enabled: true
  parallelism: 1

MultiVideoGridJob:
  enabled: true
  parallelism: 2

VideoReaderJob:
  enabled: true
  parallelism: 2
