flink:
  cluster:
    replicas: 1
    taskManager:
      replicas: 1
      memory: 4G
      cpu: 900m
      taskSlots: 6

mavenCoordinate:
  group: io.pravega.example.video
  artifact: flinkprocessor
  version: 0.1.0

VideoDataGeneratorJob:
  enabled: true
  parallelism: 1

MultiVideoGridJob:
  enabled: true
  parallelism: 2
  input:
    stream: video1
    minNumSegments: 6
  output:
    stream: grid1
    minNumSegments: 3

VideoReaderJob:
  enabled: true
  parallelism: 2
