VideoDataGeneratorJob:
  parallelism: 12
  enableOperatorChaining: "true"
  useCachedFrame: "true"
  numCameras: 96
  imageWidth: 450
  chunkSizeBytes: 524288
  taskManager:
    replicas: 4
    memory: 2G
    cpu: 1500m
    taskSlots: 3

MultiVideoGridJob:
  enabled: false
  input:
    stream: video1
    minNumSegments: 42

VideoReaderJob:
  enabled: false
