kind: Pod
apiVersion: v1
metadata:
  name: benchmark-bookkeeper-1
spec:
  containers:
    - name: bookkeeper-benchmark
      image: nautperf/bookkeeper-bmrk:4.7.3
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "2"
          memory: "2Gi"
        requests:
          cpu: "2"
          memory: "2Gi"
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
      env:
        - name: BENCHMARK_EXTRA_OPTS
          value: -Dorg.apache.bookkeeper.conf.readsystemproperties=true -DzkLedgersRootPath=/pravega/pravega/bookkeeper/ledgers
        - name: BENCHMARK_EXTRA_CLASSPATH
          value: /opt/bookkeeper/bookkeeper-benchmark/target/bookkeeper-benchmark-4.7.3.jar
