kind: Job
apiVersion: batch/v1
metadata:
  name: pravega-benchmark
spec:
  parallelism: 5
  template:
    spec:
      serviceAccount: examples-pravega
      restartPolicy: Never
      containers:
        - name: benchmark
          image: nautperf/bmrk:0.5.0-2299.8779f22s
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          args: [
            "pravega-benchmark",
            "-controller", "tcp://nautilus-pravega-controller.nautilus-pravega.svc.cluster.local:9090",
            "-scope", "examples",
            "-stream", "benchmark1",
#            "-recreate", "1",
            "-segments", "42",
            "-producers", "1",
            "-time", "14400",  # Number of seconds to run
            "-size", "524288",
            "-throughput", "20",
          ]
          env:
            - name: JAVA_OPTS
              value: "-Xmx2g -Xms1g"
            - name: pravega_client_auth_method
              value: Bearer
            - name: pravega_client_auth_loadDynamic
              value: "true"
